spring.application.name=PruebaTecnica
# src/main/resources/application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/pruebaTecnica_Karimnot
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs de seguridad
logging.level.org.springframework.security=DEBUG
logging.level.com.example.PruebaTecnica.security=DEBUG
logging.level.org.springframework.security.web.access.intercept=DEBUG
